"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
`use client`;
require("./globals.css");
const react_1 = __importDefault(require("react"));
const google_1 = require("next/font/google");
const interFonts = (0, google_1.Inter)({
    subsets: ["latin"],
    weight: ["200", "400", "500", "600", "700", "900"]
});
exports.metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
function RootLayout({ children, }) {
    return (<html lang="en">
      <body className={interFonts.className}>
        <div>
        </div>
        <div>
          {children}
        </div>
      </body>
    </html>);
}
exports.default = RootLayout;
