"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
require("./globals.css");
exports.metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
function RootLayout({ children, }) {
    return (<html lang="en">
      <body>{children}</body>
    </html>);
}
exports.default = RootLayout;
